# Generated by Django 5.2.8 on 2025-12-01 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateField()),
                ('total_hours', models.PositiveIntegerField(default=0, help_text='Estimated total hours needed for this goal.')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topics', models.TextField(help_text='Comma-separated or free-text list of topics planned.')),
                ('planned_hours', models.PositiveIntegerField(default=1, help_text='Planned number of study hours for this day.')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(blank=True, help_text='Optional link to a broader learning goal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='planner.goal')),
            ],
        ),
    ]
